### ISSUE TITLE
Add eslint CI check

### ISSUE THREAD

**Issue by julesvirallinen** [julesvirallinen/vj-p5-live#9]
Add CI check that verifies that linter passes before allowing merge. 

Action code is like this: 

```
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
```
